### ISSUE TITLE
Lets try Sliding sync

### ISSUE THREAD

**Issue by iamtalhaasghar** [revivalistsorg/synapse#6]
Why?

Will enable users to use next gen element-x clients with our servers which loads room messages instantly.

https://element.io/labs/element-x

**Comment by iamtalhaasghar** [comment]
Another reason to try slide sync

https://github.com/element-hq/element-android/issues/8826

**Comment by iamtalhaasghar** [comment]
also,

> We currently have (or going to have) the 2 apps in the store: Element and Element X. When ready, the Element app will use the Element X code. Element X is a temporary app using a code name


 https://github.com/element-hq/element-android/issues/8606#issuecomment-1669902114

**Comment by BloodyIron** [comment]
So does this mean there's works to improve notifications for Element (non-x)? I see you tagged https://github.com/element-hq/element-android/issues/8826

**Comment by iamtalhaasghar** [comment]
@BloodyIron i think the element-hq is focusing more on element-x client and element app is in maintainance mode so i dont think there is going to be a fix for notifications issue for original element app. That issue has been open for yrs now.

**Comment by BloodyIron** [comment]
> @BloodyIron i think the element-hq is focusing more on element-x client and element app is in maintainance mode so i dont think there is going to be a fix for notifications issue for original element app any sooner.

I really don't think it's an acceptable thing to have to wait years for the new shiny app to be released to have notifications fixed. For something as core as reliable notifications, I think almost everyone would think it reasonable to have fixes done on such a thing in the "older crustier version" of Element.

I know that in plenty of cases yes, it is worth while to put the effort into the "new thing", but in this case, I do not agree that the old thing should not get love for this particular aspect. It's literally core to why anyone would use a chat app.
